export const SOCKET_URL = process.env.SOCKET_URL || "http://localhost:3005";

export const EVENTS = {
  connection: "connection",
  CLIENT: {
    START_A_CONVERSATION: "START_A_CONVERSATION",
    GET_ACTIVE_FRIENDS:'GET_ACTIVE_FRIENDS',
    TYPING_MESSAGE:'TYPING_MESSAGE',
    TYPING_MESSAGE_GET: "TYPING_MESSAGE_GET",
  },
  SERVER: {
    NEW_FRIEND: "NEW_FRIEND",
    GET_CONVERSATION_NEW_MESSAGE: "GET_CONVERSATION_NEW_MESSAGE",
    ADD_ACTIVE_USER: "ADD_ACTIVE_USER",
  },
};
