export const SOCKET_URL =
  process.env.NODE_ENV === "development"
    ? "http://localhost:3005"
    : process.env.SOCKET_URL;

export const EVENTS = {
  connection: "connection",
  CLIENT: {
    START_A_CONVERSATION: "START_A_CONVERSATION",
    GET_ACTIVE_FRIENDS: "GET_ACTIVE_FRIENDS",
    TYPING_MESSAGE: "TYPING_MESSAGE",
    TYPING_MESSAGE_GET: "TYPING_MESSAGE_GET",
    GET_CONVERSATION_NEW_MESSAGE: "GET_CONVERSATION_NEW_MESSAGE",
    CALL: 'CALL',
    INCOMING_CALL: "INCOMING_CALL",
    END_CALL: 'END_CALL',
    REJECT_CALL: 'REJECT_CALL',
    ACCEPT_CALL: 'ACCEPT_CALL',
    ACCEPTED_CALL: 'ACCEPTED_CALL',
    PEER_NEGOTIATION_NEEDED: "PEER_NEGOTIATION_NEEDED",
    PEER_NEGOTIATION_DONE: "PEER_NEGOTIATION_DONE",
    PEER_NEGOTIATION_FINAL:"PEER_NEGOTIATION_FINAL" 
  },
  SERVER: {
    NEW_FRIEND: "NEW_FRIEND",
    ACTIVE_FRIENDS: "ACTIVE_FRIENDS",
    SET_CONVERSATION_NEW_MESSAGE: "SET_CONVERSATION_NEW_MESSAGE",
    ADD_ACTIVE_USER: "ADD_ACTIVE_USER",

    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    NEW_USER_JOINED: 'NEW_USER_JOINED'
  },
};
